# Generated by Django 4.0.3 on 2022-04-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='password_model',
            name='password',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='password_model',
            name='platform',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
