# Generated by Django 4.0.3 on 2022-04-27 23:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_password_model_password_password_model_platform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='password_model',
            new_name='PasswordModel',
        ),
    ]
